#ifndef STRATEGY_CORE_GLOBAL_H
#define STRATEGY_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRATEGY_CORE_LIBRARY)
#  define STRATEGY_CORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRATEGY_CORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRATEGY_CORE_GLOBAL_H
